//Generated by EnumGenerator, 26.08.2020 11:39:27
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления Communications в строку и обратно
	/// </summary>
	public class CommunicationsStrings : IEnumStrings<Communications>
	{
		private static readonly string StrHeatingNetwork = "Теплосеть";
		private static readonly string StrWaterPipeline = "Водопровод";
		private static readonly string StrGasPipeline = "Газопровод";
		private static readonly string StrElectricCable = "Электрокабель ";
		private static readonly string StrCommunicationCable = "Кабель связи";
		private static readonly string StrTelecable = "Телекабель";

		public CommunicationsStrings() { }
		private static CommunicationsStrings instance;
		public static CommunicationsStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new CommunicationsStrings();
				}
				return instance;
			}
		}

		public string GetName(Communications communications)
		{
			switch(communications)
			{
				case Communications.HeatingNetwork:
					return StrHeatingNetwork;
				case Communications.WaterPipeline:
					return StrWaterPipeline;
				case Communications.GasPipeline:
					return StrGasPipeline;
				case Communications.ElectricCable:
					return StrElectricCable;
				case Communications.CommunicationCable:
					return StrCommunicationCable;
				case Communications.Telecable:
					return StrTelecable;
				default:
					break;
			}
			return null;
		}

		public Communications GetElement(string name)
		{
			if (name == StrHeatingNetwork)
				return Communications.HeatingNetwork;
			if (name == StrWaterPipeline)
				return Communications.WaterPipeline;
			if (name == StrGasPipeline)
				return Communications.GasPipeline;
			if (name == StrElectricCable)
				return Communications.ElectricCable;
			if (name == StrCommunicationCable)
				return Communications.CommunicationCable;
			if (name == StrTelecable)
				return Communications.Telecable;
			return Communications.Telecable;
		}
	}
}
