//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления ConstructionRoadway в строку и обратно
	/// </summary>
	public class ConstructionRoadwayStrings : IEnumStrings<ConstructionRoadway>
	{
		/// <summary>
		/// FerroconcreteSlabInMainSupStruct
		/// </summary>
		private static readonly string StrЖелезобетонная плита в составе основной несущей железобетонной конструкции = "FerroconcreteSlabInMainSupStruct";
		/// <summary>
		/// FerroconcreteSlabWithPiles
		/// </summary>
		private static readonly string StrЖелезобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях) = "FerroconcreteSlabWithPiles";
		/// <summary>
		/// FerroconcreteSlabOnPiles
		/// </summary>
		private static readonly string StrЖелезобетонная плита по балкам без объединения = "FerroconcreteSlabOnPiles";
		/// <summary>
		/// OrthotropicSlab
		/// </summary>
		private static readonly string StrОртотропная плита в составе главных и поперечных балок = "OrthotropicSlab";
		/// <summary>
		/// Wood
		/// </summary>
		private static readonly string StrДеревянная = "Wood";
		/// <summary>
		/// NoData
		/// </summary>
		private static readonly string StrНет данных = "NoData";

		public ConstructionRoadwayStrings() { }
		private static ConstructionRoadwayStrings instance;
		public static ConstructionRoadwayStrings Instance
			=> instance ?? (instance = new ConstructionRoadwayStrings());

		public string GetName(ConstructionRoadway enumElement)
		{
			switch(enumElement)
			{
				case ConstructionRoadway.Железобетонная плита в составе основной несущей железобетонной конструкции:
					return StrЖелезобетонная плита в составе основной несущей железобетонной конструкции;
				case ConstructionRoadway.Железобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях):
					return StrЖелезобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях);
				case ConstructionRoadway.Железобетонная плита по балкам без объединения:
					return StrЖелезобетонная плита по балкам без объединения;
				case ConstructionRoadway.Ортотропная плита в составе главных и поперечных балок:
					return StrОртотропная плита в составе главных и поперечных балок;
				case ConstructionRoadway.Деревянная:
					return StrДеревянная;
				case ConstructionRoadway.Нет данных:
					return StrНет данных;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public ConstructionRoadway GetElement(string name)
		{
			if (name == StrЖелезобетонная плита в составе основной несущей железобетонной конструкции)
				return ConstructionRoadway.Железобетонная плита в составе основной несущей железобетонной конструкции;
			if (name == StrЖелезобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях))
				return ConstructionRoadway.Железобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях);
			if (name == StrЖелезобетонная плита по балкам без объединения)
				return ConstructionRoadway.Железобетонная плита по балкам без объединения;
			if (name == StrОртотропная плита в составе главных и поперечных балок)
				return ConstructionRoadway.Ортотропная плита в составе главных и поперечных балок;
			if (name == StrДеревянная)
				return ConstructionRoadway.Деревянная;
			if (name == StrНет данных)
				return ConstructionRoadway.Нет данных;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
