//Generated by EnumGenerator, 02.09.2020 13:21:23
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления ConstructionRoadway в строку и обратно
	/// </summary>
	public class ConstructionRoadwayStrings : IEnumStrings<ConstructionRoadway>
	{
		private static readonly string StrFerroconcreteSlabInMainSupStruct = "Железобетонная плита в составе основной несущей железобетонной конструкции";
		private static readonly string StrFerroconcreteSlabWithPiles = "Железобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях)";
		private static readonly string StrFerroconcreteSlabOnPiles = "Железобетонная плита по балкам без объединения";
		private static readonly string StrOrthotropicSlab = "Ортотропная плита в составе главных и поперечных балок";
		private static readonly string StrWood = "Деревянная";
		private static readonly string StrNoData = "Нет данных";

		public ConstructionRoadwayStrings() { }
		private static ConstructionRoadwayStrings instance;
		public static ConstructionRoadwayStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new ConstructionRoadwayStrings();
				}
				return instance;
			}
		}

		public string GetName(ConstructionRoadway construction_roadway)
		{
			switch(construction_roadway)
			{
				case ConstructionRoadway.FerroconcreteSlabInMainSupStruct:
					return StrFerroconcreteSlabInMainSupStruct;
				case ConstructionRoadway.FerroconcreteSlabWithPiles:
					return StrFerroconcreteSlabWithPiles;
				case ConstructionRoadway.FerroconcreteSlabOnPiles:
					return StrFerroconcreteSlabOnPiles;
				case ConstructionRoadway.OrthotropicSlab:
					return StrOrthotropicSlab;
				case ConstructionRoadway.Wood:
					return StrWood;
				case ConstructionRoadway.NoData:
					return StrNoData;
				default:
					break;
			}
			return null;
		}

		public ConstructionRoadway GetElement(string name)
		{
			if (name == StrFerroconcreteSlabInMainSupStruct)
				return ConstructionRoadway.FerroconcreteSlabInMainSupStruct;
			if (name == StrFerroconcreteSlabWithPiles)
				return ConstructionRoadway.FerroconcreteSlabWithPiles;
			if (name == StrFerroconcreteSlabOnPiles)
				return ConstructionRoadway.FerroconcreteSlabOnPiles;
			if (name == StrOrthotropicSlab)
				return ConstructionRoadway.OrthotropicSlab;
			if (name == StrWood)
				return ConstructionRoadway.Wood;
			if (name == StrNoData)
				return ConstructionRoadway.NoData;
			return ConstructionRoadway.NoData;
		}
	}
}
