//Generated by EnumGenerator, 25.08.2020 16:05:57
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления ConstructionRoadway в строку и обратно
	/// </summary>
	public class ConstructionRoadwayStrings : IEnumStrings<ConstructionRoadway>
	{
		private static readonly string _ferroconcrete_slab_in_main_sup_struct = "Железобетонная плита в составе основной несущей железобетонной конструкции";
		private static readonly string _ferroconcrete_slab_with_piles = "Железобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях)";
		private static readonly string _ferroconcrete_slab_on_piles = "Железобетонная плита по балкам без объединения";
		private static readonly string _orthotropic_slab = "Ортотропная плита в составе главных и поперечных балок";
		private static readonly string _wood = "Деревянная";
		private static readonly string _no_data = "Нет данных";

		public ConstructionRoadwayStrings() { }
		private static ConstructionRoadwayStrings instance;
		public static ConstructionRoadwayStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new ConstructionRoadwayStrings();
				}
				return instance;
			}
		}

		public string GetName(ConstructionRoadway construction_roadway)
		{
			switch(construction_roadway)
			{
				case ConstructionRoadway.FerroconcreteSlabInMainSupStruct:
					return _ferroconcrete_slab_in_main_sup_struct;
				case ConstructionRoadway.FerroconcreteSlabWithPiles:
					return _ferroconcrete_slab_with_piles;
				case ConstructionRoadway.FerroconcreteSlabOnPiles:
					return _ferroconcrete_slab_on_piles;
				case ConstructionRoadway.OrthotropicSlab:
					return _orthotropic_slab;
				case ConstructionRoadway.Wood:
					return _wood;
				case ConstructionRoadway.NoData:
					return _no_data;
				default:
					break;
			}
			return null;
		}

		public ConstructionRoadway GetElement(string name)
		{
			if (name == _ferroconcrete_slab_in_main_sup_struct)
				return ConstructionRoadway.FerroconcreteSlabInMainSupStruct;
			if (name == _ferroconcrete_slab_with_piles)
				return ConstructionRoadway.FerroconcreteSlabWithPiles;
			if (name == _ferroconcrete_slab_on_piles)
				return ConstructionRoadway.FerroconcreteSlabOnPiles;
			if (name == _orthotropic_slab)
				return ConstructionRoadway.OrthotropicSlab;
			if (name == _wood)
				return ConstructionRoadway.Wood;
			if (name == _no_data)
				return ConstructionRoadway.NoData;
			return ConstructionRoadway.NoData;
		}
	}
}
