//Generated by EnumGenerator, 22.09.2020 12:53:34
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления CoverType в строку и обратно
	/// </summary>
	public class CoverTypeStrings : IEnumStrings<CoverType>
	{
		/// <summary>
		/// Асфальтобетон
		/// </summary>
		private static readonly string StrAsphaltConcrete = "Асфальтобетон";
		/// <summary>
		/// Цементобетон
		/// </summary>
		private static readonly string StrCementConcrete = "Цементобетон";
		/// <summary>
		/// Черный щебень
		/// </summary>
		private static readonly string StrBlackRubble = "Черный щебень";
		/// <summary>
		/// Каменная мостовая
		/// </summary>
		private static readonly string StrStonePavement = "Каменная мостовая";
		/// <summary>
		/// Дощатый настил
		/// </summary>
		private static readonly string StrBoardwalk = "Дощатый настил";
		/// <summary>
		/// Песчано-гравийная смесь
		/// </summary>
		private static readonly string StrSandAndGravel = "Песчано-гравийная смесь";
		/// <summary>
		/// Грунтовое
		/// </summary>
		private static readonly string StrGround = "Грунтовое";
		/// <summary>
		/// Ж.б. плиты по цементно-песчаной подготовке
		/// </summary>
		private static readonly string StrFerroconcreteSlabsCementSand = "Ж.б. плиты по цементно-песчаной подготовке";

		public CoverTypeStrings() { }
		private static CoverTypeStrings instance;
		public static CoverTypeStrings Instance
			=> instance ?? (instance = new CoverTypeStrings());

		public string GetName(CoverType enumElement)
		{
			switch(enumElement)
			{
				case CoverType.AsphaltConcrete:
					return StrAsphaltConcrete;
				case CoverType.CementConcrete:
					return StrCementConcrete;
				case CoverType.BlackRubble:
					return StrBlackRubble;
				case CoverType.StonePavement:
					return StrStonePavement;
				case CoverType.Boardwalk:
					return StrBoardwalk;
				case CoverType.SandAndGravel:
					return StrSandAndGravel;
				case CoverType.Ground:
					return StrGround;
				case CoverType.FerroconcreteSlabsCementSand:
					return StrFerroconcreteSlabsCementSand;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public CoverType GetElement(string name)
		{
			if (name == StrAsphaltConcrete)
				return CoverType.AsphaltConcrete;
			if (name == StrCementConcrete)
				return CoverType.CementConcrete;
			if (name == StrBlackRubble)
				return CoverType.BlackRubble;
			if (name == StrStonePavement)
				return CoverType.StonePavement;
			if (name == StrBoardwalk)
				return CoverType.Boardwalk;
			if (name == StrSandAndGravel)
				return CoverType.SandAndGravel;
			if (name == StrGround)
				return CoverType.Ground;
			if (name == StrFerroconcreteSlabsCementSand)
				return CoverType.FerroconcreteSlabsCementSand;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
