//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления CoverType в строку и обратно
	/// </summary>
	public class CoverTypeStrings : IEnumStrings<CoverType>
	{
		/// <summary>
		/// AsphaltConcrete
		/// </summary>
		private static readonly string StrАсфальтобетон = "AsphaltConcrete";
		/// <summary>
		/// CementConcrete
		/// </summary>
		private static readonly string StrЦементобетон = "CementConcrete";
		/// <summary>
		/// BlackRubble
		/// </summary>
		private static readonly string StrЧерный щебень = "BlackRubble";
		/// <summary>
		/// StonePavement
		/// </summary>
		private static readonly string StrКаменная мостовая = "StonePavement";
		/// <summary>
		/// Boardwalk
		/// </summary>
		private static readonly string StrДощатый настил = "Boardwalk";
		/// <summary>
		/// SandAndGravel
		/// </summary>
		private static readonly string StrПесчано-гравийная смесь = "SandAndGravel";
		/// <summary>
		/// Ground
		/// </summary>
		private static readonly string StrГрунтовое = "Ground";
		/// <summary>
		/// FerroconcreteSlabsCementSand
		/// </summary>
		private static readonly string StrЖ.б. плиты по цементно-песчаной подготовке = "FerroconcreteSlabsCementSand";

		public CoverTypeStrings() { }
		private static CoverTypeStrings instance;
		public static CoverTypeStrings Instance
			=> instance ?? (instance = new CoverTypeStrings());

		public string GetName(CoverType enumElement)
		{
			switch(enumElement)
			{
				case CoverType.Асфальтобетон:
					return StrАсфальтобетон;
				case CoverType.Цементобетон:
					return StrЦементобетон;
				case CoverType.Черный щебень:
					return StrЧерный щебень;
				case CoverType.Каменная мостовая:
					return StrКаменная мостовая;
				case CoverType.Дощатый настил:
					return StrДощатый настил;
				case CoverType.Песчано-гравийная смесь:
					return StrПесчано-гравийная смесь;
				case CoverType.Грунтовое:
					return StrГрунтовое;
				case CoverType.Ж.б. плиты по цементно-песчаной подготовке:
					return StrЖ.б. плиты по цементно-песчаной подготовке;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public CoverType GetElement(string name)
		{
			if (name == StrАсфальтобетон)
				return CoverType.Асфальтобетон;
			if (name == StrЦементобетон)
				return CoverType.Цементобетон;
			if (name == StrЧерный щебень)
				return CoverType.Черный щебень;
			if (name == StrКаменная мостовая)
				return CoverType.Каменная мостовая;
			if (name == StrДощатый настил)
				return CoverType.Дощатый настил;
			if (name == StrПесчано-гравийная смесь)
				return CoverType.Песчано-гравийная смесь;
			if (name == StrГрунтовое)
				return CoverType.Грунтовое;
			if (name == StrЖ.б. плиты по цементно-песчаной подготовке)
				return CoverType.Ж.б. плиты по цементно-песчаной подготовке;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
