//Generated by EnumGenerator, 22.09.2020 12:53:34
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления CrossJoinMethod в строку и обратно
	/// </summary>
	public class CrossJoinMethodStrings : IEnumStrings<CrossJoinMethod>
	{
		/// <summary>
		/// Не объединены
		/// </summary>
		private static readonly string StrNone = "Не объединены";
		/// <summary>
		/// По шпонкам
		/// </summary>
		private static readonly string StrDowels = "По шпонкам";
		/// <summary>
		/// По диафрагмам
		/// </summary>
		private static readonly string StrDiaphragms = "По диафрагмам";
		/// <summary>
		/// По плите
		/// </summary>
		private static readonly string StrStove = "По плите";
		/// <summary>
		/// По плите и диафрагмам
		/// </summary>
		private static readonly string StrPlateAndDiaphragms = "По плите и диафрагмам";
		/// <summary>
		/// По поперечным балкам и связям
		/// </summary>
		private static readonly string StrTransverseBeamsAndTies = "По поперечным балкам и связям";
		/// <summary>
		/// По продольным и поперечным связям
		/// </summary>
		private static readonly string StrLongitudinalAndTransverseLinks = "По продольным и поперечным связям";
		/// <summary>
		/// По плите и поперечным связям
		/// </summary>
		private static readonly string StrSlabAndCrossBraces = "По плите и поперечным связям";
		/// <summary>
		/// Нет данных
		/// </summary>
		private static readonly string StrNoData = "Нет данных";

		public CrossJoinMethodStrings() { }
		private static CrossJoinMethodStrings instance;
		public static CrossJoinMethodStrings Instance
			=> instance ?? (instance = new CrossJoinMethodStrings());

		public string GetName(CrossJoinMethod enumElement)
		{
			switch(enumElement)
			{
				case CrossJoinMethod.None:
					return StrNone;
				case CrossJoinMethod.Dowels:
					return StrDowels;
				case CrossJoinMethod.Diaphragms:
					return StrDiaphragms;
				case CrossJoinMethod.Stove:
					return StrStove;
				case CrossJoinMethod.PlateAndDiaphragms:
					return StrPlateAndDiaphragms;
				case CrossJoinMethod.TransverseBeamsAndTies:
					return StrTransverseBeamsAndTies;
				case CrossJoinMethod.LongitudinalAndTransverseLinks:
					return StrLongitudinalAndTransverseLinks;
				case CrossJoinMethod.SlabAndCrossBraces:
					return StrSlabAndCrossBraces;
				case CrossJoinMethod.NoData:
					return StrNoData;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public CrossJoinMethod GetElement(string name)
		{
			if (name == StrNone)
				return CrossJoinMethod.None;
			if (name == StrDowels)
				return CrossJoinMethod.Dowels;
			if (name == StrDiaphragms)
				return CrossJoinMethod.Diaphragms;
			if (name == StrStove)
				return CrossJoinMethod.Stove;
			if (name == StrPlateAndDiaphragms)
				return CrossJoinMethod.PlateAndDiaphragms;
			if (name == StrTransverseBeamsAndTies)
				return CrossJoinMethod.TransverseBeamsAndTies;
			if (name == StrLongitudinalAndTransverseLinks)
				return CrossJoinMethod.LongitudinalAndTransverseLinks;
			if (name == StrSlabAndCrossBraces)
				return CrossJoinMethod.SlabAndCrossBraces;
			if (name == StrNoData)
				return CrossJoinMethod.NoData;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
