//Generated by EnumGenerator, 27.08.2020 16:47:03
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления DrainageType в строку и обратно
	/// </summary>
	public class DrainageTypeStrings : IEnumStrings<DrainageType>
	{
		private static readonly string StrNone = "Водоотвод не организован";
		private static readonly string StrDrainPipesDischargeUnderBridge = "Через водоотводные трубки со сбросом под мостовое сооружение";
		private static readonly string StrDrainPipesWaterSupply = "Через водоотводные трубки с отводом воды по водопроводу (лотку, трубе) вдоль мостового сооружения";
		private static readonly string StrWaterSlopes = "Сток воды вдоль проезжей части за счет уклонов за пределы мостового сооружения";
		private static readonly string StrWaterDischargeSidewalks = "Сброс воды поперек мостового сооружения через тротуары";
		private static readonly string StrByTrays = "По лоткам (продольным или поперечным) за пределы мостового сооружения";
		private static readonly string StrTheGapsCarriageway = "Через зазоры в проезжей части мостового сооружения (дощатый настил и т. д.)";
		private static readonly string StrCombined = "Комбинированный (например, за счет уклонов и лотков)";
		private static readonly string StrNoData = "Нет данных";

		public DrainageTypeStrings() { }
		private static DrainageTypeStrings instance;
		public static DrainageTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new DrainageTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(DrainageType drainage_type)
		{
			switch(drainage_type)
			{
				case DrainageType.None:
					return StrNone;
				case DrainageType.DrainPipesDischargeUnderBridge:
					return StrDrainPipesDischargeUnderBridge;
				case DrainageType.DrainPipesWaterSupply:
					return StrDrainPipesWaterSupply;
				case DrainageType.WaterSlopes:
					return StrWaterSlopes;
				case DrainageType.WaterDischargeSidewalks:
					return StrWaterDischargeSidewalks;
				case DrainageType.ByTrays:
					return StrByTrays;
				case DrainageType.TheGapsCarriageway:
					return StrTheGapsCarriageway;
				case DrainageType.Combined:
					return StrCombined;
				case DrainageType.NoData:
					return StrNoData;
				default:
					break;
			}
			return null;
		}

		public DrainageType GetElement(string name)
		{
			if (name == StrNone)
				return DrainageType.None;
			if (name == StrDrainPipesDischargeUnderBridge)
				return DrainageType.DrainPipesDischargeUnderBridge;
			if (name == StrDrainPipesWaterSupply)
				return DrainageType.DrainPipesWaterSupply;
			if (name == StrWaterSlopes)
				return DrainageType.WaterSlopes;
			if (name == StrWaterDischargeSidewalks)
				return DrainageType.WaterDischargeSidewalks;
			if (name == StrByTrays)
				return DrainageType.ByTrays;
			if (name == StrTheGapsCarriageway)
				return DrainageType.TheGapsCarriageway;
			if (name == StrCombined)
				return DrainageType.Combined;
			if (name == StrNoData)
				return DrainageType.NoData;
			return DrainageType.NoData;
		}
	}
}
