//Generated by EnumGenerator, 22.09.2020 12:43:25
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления ProtectionType в строку и обратно
	/// </summary>
	public class ProtectionTypeStrings : IEnumStrings<ProtectionType>
	{
		/// <summary>
		/// Парапетное
		/// </summary>
		private static readonly string StrParapet = "Парапетное";
		/// <summary>
		/// Барьерное
		/// </summary>
		private static readonly string StrBarrier = "Барьерное";
		/// <summary>
		/// Бордюрное
		/// </summary>
		private static readonly string StrBorder = "Бордюрное";
		/// <summary>
		/// Тросовое
		/// </summary>
		private static readonly string StrCable = "Тросовое";
		/// <summary>
		/// Комбинированное
		/// </summary>
		private static readonly string StrCombined = "Комбинированное";
		/// <summary>
		/// Нет данных
		/// </summary>
		private static readonly string StrNoData = "Нет данных";

		public ProtectionTypeStrings() { }
		private static ProtectionTypeStrings instance;
		public static ProtectionTypeStrings Instance
			=> instance ?? (instance = new ProtectionTypeStrings());

		public string GetName(ProtectionType enumElement)
		{
			switch(enumElement)
			{
				case ProtectionType.Parapet:
					return StrParapet;
				case ProtectionType.Barrier:
					return StrBarrier;
				case ProtectionType.Border:
					return StrBorder;
				case ProtectionType.Cable:
					return StrCable;
				case ProtectionType.Combined:
					return StrCombined;
				case ProtectionType.NoData:
					return StrNoData;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public ProtectionType GetElement(string name)
		{
			if (name == StrParapet)
				return ProtectionType.Parapet;
			if (name == StrBarrier)
				return ProtectionType.Barrier;
			if (name == StrBorder)
				return ProtectionType.Border;
			if (name == StrCable)
				return ProtectionType.Cable;
			if (name == StrCombined)
				return ProtectionType.Combined;
			if (name == StrNoData)
				return ProtectionType.NoData;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
