//Generated by EnumGenerator, 25.08.2020 10:59:08
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления ProtectionType в строку и обратно
	/// </summary>
	public class ProtectionTypeStrings : IEnumStrings<ProtectionType>
	{
		 public static Dictionary<ProtectionType, string> Strings =
			 new Dictionary<ProtectionType, string> {
				 { ProtectionType.Parapet,"Парапетное" },
				 { ProtectionType.Barrier,"Барьерное" },
				 { ProtectionType.Border,"Бордюрное" },
				 { ProtectionType.Cable,"Тросовое" },
				 { ProtectionType.Combined,"Комбинированное" },
				 { ProtectionType.NoData,"Нет данных" },
			};
		public ProtectionTypeStrings() { }
		private static ProtectionTypeStrings instance;
		public static ProtectionTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new ProtectionTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(ProtectionType protection_type)
		{
			return Strings[protection_type];
		}
		public ProtectionType GetElement(string name)
		{
			return Strings.FirstOrDefault(s => s.Value == name).Key;
		}
	}
}
