//Generated by EnumGenerator, 25.08.2020 16:05:57
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления RailingsType в строку и обратно
	/// </summary>
	public class RailingsTypeStrings : IEnumStrings<RailingsType>
	{
		private static readonly string _none = "Перила отсутствуют";
		private static readonly string _metallic = "Металлические (секционные или непрерывные)";
		private static readonly string _ferroncrete_metal_grating = "Железобетонный поручень с металлической решеткой";
		private static readonly string _ferroconcrete_llattice_or_solid_wall = "Железобетонные (решетчатые или со сплошной стенкой)";
		private static readonly string _wood = "Деревянные";
		private static readonly string _combined = "Комбинированные";
		private static readonly string _no_data = "Нет данных";

		public RailingsTypeStrings() { }
		private static RailingsTypeStrings instance;
		public static RailingsTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new RailingsTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(RailingsType railings_type)
		{
			switch(railings_type)
			{
				case RailingsType.None:
					return _none;
				case RailingsType.Metallic:
					return _metallic;
				case RailingsType.FerroncreteMetalGrating:
					return _ferroncrete_metal_grating;
				case RailingsType.FerroconcreteLlatticeOrSolidWall:
					return _ferroconcrete_llattice_or_solid_wall;
				case RailingsType.Wood:
					return _wood;
				case RailingsType.Combined:
					return _combined;
				case RailingsType.NoData:
					return _no_data;
				default:
					break;
			}
			return null;
		}

		public RailingsType GetElement(string name)
		{
			if (name == _none)
				return RailingsType.None;
			if (name == _metallic)
				return RailingsType.Metallic;
			if (name == _ferroncrete_metal_grating)
				return RailingsType.FerroncreteMetalGrating;
			if (name == _ferroconcrete_llattice_or_solid_wall)
				return RailingsType.FerroconcreteLlatticeOrSolidWall;
			if (name == _wood)
				return RailingsType.Wood;
			if (name == _combined)
				return RailingsType.Combined;
			if (name == _no_data)
				return RailingsType.NoData;
			return RailingsType.NoData;
		}
	}
}
