//Generated by EnumGenerator, 02.09.2020 13:21:24
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления RailingsType в строку и обратно
	/// </summary>
	public class RailingsTypeStrings : IEnumStrings<RailingsType>
	{
		private static readonly string StrNone = "Перила отсутствуют";
		private static readonly string StrMetallic = "Металлические (секционные или непрерывные)";
		private static readonly string StrFerroncreteMetalGrating = "Железобетонный поручень с металлической решеткой";
		private static readonly string StrFerroconcreteLlatticeOrSolidWall = "Железобетонные (решетчатые или со сплошной стенкой)";
		private static readonly string StrWood = "Деревянные";
		private static readonly string StrCombined = "Комбинированные";
		private static readonly string StrNoData = "Нет данных";

		public RailingsTypeStrings() { }
		private static RailingsTypeStrings instance;
		public static RailingsTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new RailingsTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(RailingsType railings_type)
		{
			switch(railings_type)
			{
				case RailingsType.None:
					return StrNone;
				case RailingsType.Metallic:
					return StrMetallic;
				case RailingsType.FerroncreteMetalGrating:
					return StrFerroncreteMetalGrating;
				case RailingsType.FerroconcreteLlatticeOrSolidWall:
					return StrFerroconcreteLlatticeOrSolidWall;
				case RailingsType.Wood:
					return StrWood;
				case RailingsType.Combined:
					return StrCombined;
				case RailingsType.NoData:
					return StrNoData;
				default:
					break;
			}
			return null;
		}

		public RailingsType GetElement(string name)
		{
			if (name == StrNone)
				return RailingsType.None;
			if (name == StrMetallic)
				return RailingsType.Metallic;
			if (name == StrFerroncreteMetalGrating)
				return RailingsType.FerroncreteMetalGrating;
			if (name == StrFerroconcreteLlatticeOrSolidWall)
				return RailingsType.FerroconcreteLlatticeOrSolidWall;
			if (name == StrWood)
				return RailingsType.Wood;
			if (name == StrCombined)
				return RailingsType.Combined;
			if (name == StrNoData)
				return RailingsType.NoData;
			return RailingsType.NoData;
		}
	}
}
