//Generated by EnumGenerator, 22.09.2020 12:53:34
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления RegulatoryStructures в строку и обратно
	/// </summary>
	public class RegulatoryStructuresStrings : IEnumStrings<RegulatoryStructures>
	{
		/// <summary>
		/// Струенаправляющая дамба с различными видами укрепления откосов
		/// </summary>
		private static readonly string StrJetGuideSlopeReinforcement = "Струенаправляющая дамба с различными видами укрепления откосов";
		/// <summary>
		/// Струенаправляющая дамба с траверсами
		/// </summary>
		private static readonly string StrJetGuideWithTraverses = "Струенаправляющая дамба с траверсами";
		/// <summary>
		/// Укрепление берега различными конструкциями
		/// </summary>
		private static readonly string StrStrengtheningCoastVariousStructures = "Укрепление берега различными конструкциями";
		/// <summary>
		/// Струенаправляющая дамба и укрепление берега
		/// </summary>
		private static readonly string StrJetGuideShoreReinforcement = "Струенаправляющая дамба и укрепление берега";
		/// <summary>
		/// Конус
		/// </summary>
		private static readonly string StrCone = "Конус";
		/// <summary>
		/// Подпорная или заборная стенка
		/// </summary>
		private static readonly string StrRetainingOrFenceWall = "Подпорная или заборная стенка";
		/// <summary>
		/// Регуляционных сооружений нет
		/// </summary>
		private static readonly string StrNone = "Регуляционных сооружений нет";

		public RegulatoryStructuresStrings() { }
		private static RegulatoryStructuresStrings instance;
		public static RegulatoryStructuresStrings Instance
			=> instance ?? (instance = new RegulatoryStructuresStrings());

		public string GetName(RegulatoryStructures enumElement)
		{
			switch(enumElement)
			{
				case RegulatoryStructures.JetGuideSlopeReinforcement:
					return StrJetGuideSlopeReinforcement;
				case RegulatoryStructures.JetGuideWithTraverses:
					return StrJetGuideWithTraverses;
				case RegulatoryStructures.StrengtheningCoastVariousStructures:
					return StrStrengtheningCoastVariousStructures;
				case RegulatoryStructures.JetGuideShoreReinforcement:
					return StrJetGuideShoreReinforcement;
				case RegulatoryStructures.Cone:
					return StrCone;
				case RegulatoryStructures.RetainingOrFenceWall:
					return StrRetainingOrFenceWall;
				case RegulatoryStructures.None:
					return StrNone;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public RegulatoryStructures GetElement(string name)
		{
			if (name == StrJetGuideSlopeReinforcement)
				return RegulatoryStructures.JetGuideSlopeReinforcement;
			if (name == StrJetGuideWithTraverses)
				return RegulatoryStructures.JetGuideWithTraverses;
			if (name == StrStrengtheningCoastVariousStructures)
				return RegulatoryStructures.StrengtheningCoastVariousStructures;
			if (name == StrJetGuideShoreReinforcement)
				return RegulatoryStructures.JetGuideShoreReinforcement;
			if (name == StrCone)
				return RegulatoryStructures.Cone;
			if (name == StrRetainingOrFenceWall)
				return RegulatoryStructures.RetainingOrFenceWall;
			if (name == StrNone)
				return RegulatoryStructures.None;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
