//Generated by EnumGenerator, 25.08.2020 10:59:08
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления SidewalkType в строку и обратно
	/// </summary>
	public class SidewalkTypeStrings : IEnumStrings<SidewalkType>
	{
		 public static Dictionary<SidewalkType, string> Strings =
			 new Dictionary<SidewalkType, string> {
				 { SidewalkType.None,"Тротуаров нет (зоны для прохода пешеходов)" },
				 { SidewalkType.Metallic,"Металлические (секционные или непрерывные)" },
				 { SidewalkType.FerroncreteMetalGrating,"Железобетонный поручень с металлической решеткой" },
				 { SidewalkType.FerroconcreteLlatticeOrSolidWall,"Железобетонные (решетчатые или со сплошной стенкой)" },
				 { SidewalkType.Wood,"Деревянные" },
				 { SidewalkType.Combined,"Комбинированные" },
				 { SidewalkType.NoData,"Нет данных" },
			};
		public SidewalkTypeStrings() { }
		private static SidewalkTypeStrings instance;
		public static SidewalkTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new SidewalkTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(SidewalkType sidewalk_type)
		{
			return Strings[sidewalk_type];
		}
		public SidewalkType GetElement(string name)
		{
			return Strings.FirstOrDefault(s => s.Value == name).Key;
		}
	}
}
