//Generated by EnumGenerator, 26.08.2020 10:15:25
using ITS.Core.Bridges.Domain.Enums;
using System.Collections.Generic;
using System.Linq;

namespace ITS.Core.Bridges.Domain.EnumStrings
{
	/// <summary>
	/// Класс-преобразователь перечисления SidewalkType в строку и обратно
	/// </summary>
	public class SidewalkTypeStrings : IEnumStrings<SidewalkType>
	{
		private static readonly string StrNone = "Тротуаров нет (зоны для прохода пешеходов)";
		private static readonly string StrMetallic = "Металлические (секционные или непрерывные)";
		private static readonly string StrFerroncreteMetalGrating = "Железобетонный поручень с металлической решеткой";
		private static readonly string StrFerroconcreteLlatticeOrSolidWall = "Железобетонные (решетчатые или со сплошной стенкой)";
		private static readonly string StrWood = "Деревянные";
		private static readonly string StrCombined = "Комбинированные";
		private static readonly string StrNoData = "Нет данных";

		public SidewalkTypeStrings() { }
		private static SidewalkTypeStrings instance;
		public static SidewalkTypeStrings Instance
		{
			get
			{
				if (instance == null)
				{
					instance = new SidewalkTypeStrings();
				}
				return instance;
			}
		}

		public string GetName(SidewalkType sidewalk_type)
		{
			switch(sidewalk_type)
			{
				case SidewalkType.None:
					return StrNone;
				case SidewalkType.Metallic:
					return StrMetallic;
				case SidewalkType.FerroncreteMetalGrating:
					return StrFerroncreteMetalGrating;
				case SidewalkType.FerroconcreteLlatticeOrSolidWall:
					return StrFerroconcreteLlatticeOrSolidWall;
				case SidewalkType.Wood:
					return StrWood;
				case SidewalkType.Combined:
					return StrCombined;
				case SidewalkType.NoData:
					return StrNoData;
				default:
					break;
			}
			return null;
		}

		public SidewalkType GetElement(string name)
		{
			if (name == StrNone)
				return SidewalkType.None;
			if (name == StrMetallic)
				return SidewalkType.Metallic;
			if (name == StrFerroncreteMetalGrating)
				return SidewalkType.FerroncreteMetalGrating;
			if (name == StrFerroconcreteLlatticeOrSolidWall)
				return SidewalkType.FerroconcreteLlatticeOrSolidWall;
			if (name == StrWood)
				return SidewalkType.Wood;
			if (name == StrCombined)
				return SidewalkType.Combined;
			if (name == StrNoData)
				return SidewalkType.NoData;
			return SidewalkType.NoData;
		}
	}
}
