//Generated by EnumGenerator, 22.09.2020 12:43:26
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления Strenghtening в строку и обратно
	/// </summary>
	public class StrenghteningStrings : IEnumStrings<Strenghtening>
	{
		/// <summary>
		/// Одерновка
		/// </summary>
		private static readonly string StrOdernovka = "Одерновка";
		/// <summary>
		/// Каменная наброска, мощение
		/// </summary>
		private static readonly string StrRoughPaving = "Каменная наброска, мощение";
		/// <summary>
		/// Монолитный бетон
		/// </summary>
		private static readonly string StrMonolithicConcrete = "Монолитный бетон";
		/// <summary>
		/// Сборные ж.б. плиты
		/// </summary>
		private static readonly string StrFerroconcreteSlabs = "Сборные ж.б. плиты";
		/// <summary>
		/// Тюфяки, матрасы-рено
		/// </summary>
		private static readonly string StrMattresses = "Тюфяки, матрасы-рено";
		/// <summary>
		/// Решетчатые ж.б. конструкции с щебеночной засыпкой
		/// </summary>
		private static readonly string StrLatticeFerroconcreteGravelBackfill = "Решетчатые ж.б. конструкции с щебеночной засыпкой";
		/// <summary>
		/// Габионы
		/// </summary>
		private static readonly string StrGabions = "Габионы";
		/// <summary>
		/// Геотекстиль с щебеночной засыпкой
		/// </summary>
		private static readonly string StrGeotextileGravelBackfill = "Геотекстиль с щебеночной засыпкой";
		/// <summary>
		/// Нет укрепления
		/// </summary>
		private static readonly string StrNone = "Нет укрепления";

		public StrenghteningStrings() { }
		private static StrenghteningStrings instance;
		public static StrenghteningStrings Instance
			=> instance ?? (instance = new StrenghteningStrings());

		public string GetName(Strenghtening enumElement)
		{
			switch(enumElement)
			{
				case Strenghtening.Odernovka:
					return StrOdernovka;
				case Strenghtening.RoughPaving:
					return StrRoughPaving;
				case Strenghtening.MonolithicConcrete:
					return StrMonolithicConcrete;
				case Strenghtening.FerroconcreteSlabs:
					return StrFerroconcreteSlabs;
				case Strenghtening.Mattresses:
					return StrMattresses;
				case Strenghtening.LatticeFerroconcreteGravelBackfill:
					return StrLatticeFerroconcreteGravelBackfill;
				case Strenghtening.Gabions:
					return StrGabions;
				case Strenghtening.GeotextileGravelBackfill:
					return StrGeotextileGravelBackfill;
				case Strenghtening.None:
					return StrNone;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public Strenghtening GetElement(string name)
		{
			if (name == StrOdernovka)
				return Strenghtening.Odernovka;
			if (name == StrRoughPaving)
				return Strenghtening.RoughPaving;
			if (name == StrMonolithicConcrete)
				return Strenghtening.MonolithicConcrete;
			if (name == StrFerroconcreteSlabs)
				return Strenghtening.FerroconcreteSlabs;
			if (name == StrMattresses)
				return Strenghtening.Mattresses;
			if (name == StrLatticeFerroconcreteGravelBackfill)
				return Strenghtening.LatticeFerroconcreteGravelBackfill;
			if (name == StrGabions)
				return Strenghtening.Gabions;
			if (name == StrGeotextileGravelBackfill)
				return Strenghtening.GeotextileGravelBackfill;
			if (name == StrNone)
				return Strenghtening.None;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
