//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления Strenghtening в строку и обратно
	/// </summary>
	public class StrenghteningStrings : IEnumStrings<Strenghtening>
	{
		/// <summary>
		/// Odernovka
		/// </summary>
		private static readonly string StrОдерновка = "Odernovka";
		/// <summary>
		/// RoughPaving
		/// </summary>
		private static readonly string StrКаменная наброска, мощение = "RoughPaving";
		/// <summary>
		/// MonolithicConcrete
		/// </summary>
		private static readonly string StrМонолитный бетон = "MonolithicConcrete";
		/// <summary>
		/// FerroconcreteSlabs
		/// </summary>
		private static readonly string StrСборные ж.б. плиты = "FerroconcreteSlabs";
		/// <summary>
		/// Mattresses
		/// </summary>
		private static readonly string StrТюфяки, матрасы-рено = "Mattresses";
		/// <summary>
		/// LatticeFerroconcreteGravelBackfill
		/// </summary>
		private static readonly string StrРешетчатые ж.б. конструкции с щебеночной засыпкой = "LatticeFerroconcreteGravelBackfill";
		/// <summary>
		/// Gabions
		/// </summary>
		private static readonly string StrГабионы = "Gabions";
		/// <summary>
		/// GeotextileGravelBackfill
		/// </summary>
		private static readonly string StrГеотекстиль с щебеночной засыпкой = "GeotextileGravelBackfill";
		/// <summary>
		/// None
		/// </summary>
		private static readonly string StrНет укрепления = "None";

		public StrenghteningStrings() { }
		private static StrenghteningStrings instance;
		public static StrenghteningStrings Instance
			=> instance ?? (instance = new StrenghteningStrings());

		public string GetName(Strenghtening enumElement)
		{
			switch(enumElement)
			{
				case Strenghtening.Одерновка:
					return StrОдерновка;
				case Strenghtening.Каменная наброска, мощение:
					return StrКаменная наброска, мощение;
				case Strenghtening.Монолитный бетон:
					return StrМонолитный бетон;
				case Strenghtening.Сборные ж.б. плиты:
					return StrСборные ж.б. плиты;
				case Strenghtening.Тюфяки, матрасы-рено:
					return StrТюфяки, матрасы-рено;
				case Strenghtening.Решетчатые ж.б. конструкции с щебеночной засыпкой:
					return StrРешетчатые ж.б. конструкции с щебеночной засыпкой;
				case Strenghtening.Габионы:
					return StrГабионы;
				case Strenghtening.Геотекстиль с щебеночной засыпкой:
					return StrГеотекстиль с щебеночной засыпкой;
				case Strenghtening.Нет укрепления:
					return StrНет укрепления;
			}
			throw new ArgumentException("Некорректный элемент перечисления", "enumElement");
		}

		public Strenghtening GetElement(string name)
		{
			if (name == StrОдерновка)
				return Strenghtening.Одерновка;
			if (name == StrКаменная наброска, мощение)
				return Strenghtening.Каменная наброска, мощение;
			if (name == StrМонолитный бетон)
				return Strenghtening.Монолитный бетон;
			if (name == StrСборные ж.б. плиты)
				return Strenghtening.Сборные ж.б. плиты;
			if (name == StrТюфяки, матрасы-рено)
				return Strenghtening.Тюфяки, матрасы-рено;
			if (name == StrРешетчатые ж.б. конструкции с щебеночной засыпкой)
				return Strenghtening.Решетчатые ж.б. конструкции с щебеночной засыпкой;
			if (name == StrГабионы)
				return Strenghtening.Габионы;
			if (name == StrГеотекстиль с щебеночной засыпкой)
				return Strenghtening.Геотекстиль с щебеночной засыпкой;
			if (name == StrНет укрепления)
				return Strenghtening.Нет укрепления;
			throw new ArgumentException("Некорректная входная строка", "name");
		}
	}
}
