//Generated by EnumGenerator, 22.09.2020 12:43:26
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления Test1 в строку и обратно
	/// </summary>
	public class Test1Strings : IEnumStrings<Test1>
	{
		/// <summary>
		/// Тест1
		/// </summary>
		private static readonly string StrTest1 = "Тест1";
		/// <summary>
		/// Тест1
		/// </summary>
		private static readonly string StrTest1 = "Тест1";
		/// <summary>
		/// Тест1
		/// </summary>
		private static readonly string StrTest1 = "Тест1";
		/// <summary>
		/// Тест1
		/// </summary>
		private static readonly string StrTest1 = "Тест1";
		/// <summary>
		/// Тест1
		/// </summary>
		private static readonly string StrTest1 = "Тест1";
		private static readonly StringBuilder stringBuilder = new StringBuilder();

		public Test1Strings() { }
		private static Test1Strings instance;
		public static Test1Strings Instance
			=> instance ?? (instance = new Test1Strings());

		public string GetName(Test1 test1)
		{
			stringBuilder.Clear();
			bool first = true;
			if(test1 == Test1.NoData)
			{
				return "Нет данных";
			}
			if ((test1 & Test1.Test1) == Test1.Test1)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest1);
				first = false;
			}
			if ((test1 & Test1.Test1) == Test1.Test1)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest1);
				first = false;
			}
			if ((test1 & Test1.Test1) == Test1.Test1)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest1);
				first = false;
			}
			if ((test1 & Test1.Test1) == Test1.Test1)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest1);
				first = false;
			}
			if ((test1 & Test1.Test1) == Test1.Test1)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest1);
				first = false;
			}
			return stringBuilder.ToString();
		}

		public Test1 GetElement(string name)
		{
			var tmp = name.Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries);
			var res = Test1.NoData;
			foreach (var item in tmp)
			{
				if (item.Equals(StrTest1, StringComparison.OrdinalIgnoreCase))
					res |= Test1.Test1;
				else if (item.Equals(StrTest1, StringComparison.OrdinalIgnoreCase))
					res |= Test1.Test1;
				else if (item.Equals(StrTest1, StringComparison.OrdinalIgnoreCase))
					res |= Test1.Test1;
				else if (item.Equals(StrTest1, StringComparison.OrdinalIgnoreCase))
					res |= Test1.Test1;
				else if (item.Equals(StrTest1, StringComparison.OrdinalIgnoreCase))
					res |= Test1.Test1;
			}
			return res;
		}
	}
}
