//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;
using System.Text;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Класс-преобразователь перечисления Test2 в строку и обратно
	/// </summary>
	public class Test2Strings : IEnumStrings<Test2>
	{
		/// <summary>
		/// Тест2
		/// </summary>
		private static readonly string StrTest2 = "Тест2";
		/// <summary>
		/// Тест2
		/// </summary>
		private static readonly string StrTest2 = "Тест2";
		/// <summary>
		/// Тест2
		/// </summary>
		private static readonly string StrTest2 = "Тест2";
		private static readonly StringBuilder stringBuilder = new StringBuilder();

		public Test2Strings() { }
		private static Test2Strings instance;
		public static Test2Strings Instance
			=> instance ?? (instance = new Test2Strings());

		public string GetName(Test2 test2)
		{
			stringBuilder.Clear();
			bool first = true;
			if(test2 == Test2.NoData)
			{
				return "Нет данных";
			}
			if ((test2 & Test2.Test2) == Test2.Test2)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest2);
				first = false;
			}
			if ((test2 & Test2.Test2) == Test2.Test2)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest2);
				first = false;
			}
			if ((test2 & Test2.Test2) == Test2.Test2)
			{
				if(!first) stringBuilder.Append(", ");
				stringBuilder.Append(StrTest2);
				first = false;
			}
			return stringBuilder.ToString();
		}

		public Test2 GetElement(string name)
		{
			var tmp = name.Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries);
			var res = Test2.NoData;
			foreach (var item in tmp)
			{
				if (item == StrTest2)
					res |= Test2.Test2;
				else if (item == StrTest2)
					res |= Test2.Test2;
				else if (item == StrTest2)
					res |= Test2.Test2;
			}
			return res;
		}
	}
}
