//Generated by EnumGenerator, 26.08.2020 11:39:27
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Обустройство
	/// </summary>
	[Serializable]
	public enum Arrangements
	{
		/// <summary>
		/// Тележки смотровые
		/// </summary>
		InspectionTrolleys,
		/// <summary>
		/// Люльки
		/// </summary>
		Cradles,
		/// <summary>
		/// Смотровые хода
		/// </summary>
		ObservationMoves,
		/// <summary>
		/// Люки
		/// </summary>
		Hatches,
		/// <summary>
		/// Двери
		/// </summary>
		Doors,
		/// <summary>
		/// Лестницы
		/// </summary>
		Stairs,
	}
}
