//Generated by EnumGenerator, 24.08.2020 16:45:41
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Статус объекта
	/// </summary>
	[Serializable]
	public enum BridgeStatus
	{
		/// <summary>
		/// Установлен
		/// </summary>
		Set,
		/// <summary>
		/// Требуется
		/// </summary>
		Required,
		/// <summary>
		/// Демонтировать
		/// </summary>
		Dismantle,
		/// <summary>
		/// Ремонт
		/// </summary>
		Repairs,
		/// <summary>
		/// Временный
		/// </summary>
		Temporary,
	}
}
