//Generated by EnumGenerator, 27.08.2020 16:47:03
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Опорная часть
	/// </summary>
	[Serializable]
	public enum BridgeSupportSpanType
	{
		/// <summary>
		/// Эластомерная
		/// </summary>
		Elastomeric,
		/// <summary>
		/// Металлическая
		/// </summary>
		Metal,
		/// <summary>
		/// Комбинированная
		/// </summary>
		Combined,
		/// <summary>
		/// Прочее
		/// </summary>
		Other,
		/// <summary>
		/// Нет данных
		/// </summary>
		NoData,
	}
}
