//Generated by EnumGenerator, 26.08.2020 11:39:27
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Коммуникации
	/// </summary>
	[Serializable]
	public enum Communications
	{
		/// <summary>
		/// Теплосеть
		/// </summary>
		HeatingNetwork,
		/// <summary>
		/// Водопровод
		/// </summary>
		WaterPipeline,
		/// <summary>
		/// Газопровод
		/// </summary>
		GasPipeline,
		/// <summary>
		/// Электрокабель 
		/// </summary>
		ElectricCable,
		/// <summary>
		/// Кабель связи
		/// </summary>
		CommunicationCable,
		/// <summary>
		/// Телекабель
		/// </summary>
		Telecable,
	}
}
