//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Конструкция проезжей части
	/// </summary>
	[Serializable]
	public enum ConstructionRoadway : byte
	{
		/// <summary>
		/// FerroconcreteSlabInMainSupStruct
		/// </summary>
		Железобетонная плита в составе основной несущей железобетонной конструкции,
		/// <summary>
		/// FerroconcreteSlabWithPiles
		/// </summary>
		Железобетонная плита, включенная в совместную работу с металлическими главными балками (в сталежелезобетонных пролетных строениях),
		/// <summary>
		/// FerroconcreteSlabOnPiles
		/// </summary>
		Железобетонная плита по балкам без объединения,
		/// <summary>
		/// OrthotropicSlab
		/// </summary>
		Ортотропная плита в составе главных и поперечных балок,
		/// <summary>
		/// Wood
		/// </summary>
		Деревянная,
		/// <summary>
		/// NoData
		/// </summary>
		Нет данных,
	}
}
