//Generated by EnumGenerator, 27.08.2020 16:47:03
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Тип покрытия проезжей части
	/// </summary>
	[Serializable]
	public enum CoverType
	{
		/// <summary>
		/// Асфальтобетон
		/// </summary>
		AsphaltConcrete,
		/// <summary>
		/// Цементобетон
		/// </summary>
		CementConcrete,
		/// <summary>
		/// Черный щебень
		/// </summary>
		BlackRubble,
		/// <summary>
		/// Каменная мостовая
		/// </summary>
		StonePavement,
		/// <summary>
		/// Дощатый настил
		/// </summary>
		Boardwalk,
		/// <summary>
		/// Песчано-гравийная смесь
		/// </summary>
		SandAndGravel,
		/// <summary>
		/// Грунтовое
		/// </summary>
		Ground,
		/// <summary>
		/// Ж.б. плиты по цементно-песчаной подготовке
		/// </summary>
		FerroconcreteSlabsCementSand,
	}
}
