//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Тип покрытия проезжей части
	/// </summary>
	[Serializable]
	public enum CoverType : byte
	{
		/// <summary>
		/// AsphaltConcrete
		/// </summary>
		Асфальтобетон,
		/// <summary>
		/// CementConcrete
		/// </summary>
		Цементобетон,
		/// <summary>
		/// BlackRubble
		/// </summary>
		Черный щебень,
		/// <summary>
		/// StonePavement
		/// </summary>
		Каменная мостовая,
		/// <summary>
		/// Boardwalk
		/// </summary>
		Дощатый настил,
		/// <summary>
		/// SandAndGravel
		/// </summary>
		Песчано-гравийная смесь,
		/// <summary>
		/// Ground
		/// </summary>
		Грунтовое,
		/// <summary>
		/// FerroconcreteSlabsCementSand
		/// </summary>
		Ж.б. плиты по цементно-песчаной подготовке,
	}
}
