//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Cпособ поперечного объединения
	/// </summary>
	[Serializable]
	public enum CrossJoinMethod : byte
	{
		/// <summary>
		/// None
		/// </summary>
		Не объединены,
		/// <summary>
		/// Dowels
		/// </summary>
		По шпонкам,
		/// <summary>
		/// Diaphragms
		/// </summary>
		По диафрагмам,
		/// <summary>
		/// Stove
		/// </summary>
		По плите,
		/// <summary>
		/// PlateAndDiaphragms
		/// </summary>
		По плите и диафрагмам,
		/// <summary>
		/// TransverseBeamsAndTies
		/// </summary>
		По поперечным балкам и связям,
		/// <summary>
		/// LongitudinalAndTransverseLinks
		/// </summary>
		По продольным и поперечным связям,
		/// <summary>
		/// SlabAndCrossBraces
		/// </summary>
		По плите и поперечным связям,
		/// <summary>
		/// NoData
		/// </summary>
		Нет данных,
	}
}
