//Generated by EnumGenerator, 01.09.2020 16:46:29
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Cпособ поперечного объединения
	/// </summary>
	[Serializable]
	public enum CrossJoinMethod : byte
	{
		/// <summary>
		/// Не объединены
		/// </summary>
		None,
		/// <summary>
		/// По шпонкам
		/// </summary>
		Dowels,
		/// <summary>
		/// По диафрагмам
		/// </summary>
		Diaphragms,
		/// <summary>
		/// По плите
		/// </summary>
		Stove,
		/// <summary>
		/// По плите и диафрагмам
		/// </summary>
		PlateAndDiaphragms,
		/// <summary>
		/// По поперечным балкам и связям
		/// </summary>
		TransverseBeamsAndTies,
		/// <summary>
		/// По продольным и поперечным связям
		/// </summary>
		LongitudinalAndTransverseLinks,
		/// <summary>
		/// По плите и поперечным связям
		/// </summary>
		SlabAndCrossBraces,
		/// <summary>
		/// Нет данных
		/// </summary>
		NoData,
	}
}
