//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Тип водоотвода
	/// </summary>
	[Serializable]
	public enum DrainageType : byte
	{
		/// <summary>
		/// None
		/// </summary>
		Водоотвод не организован,
		/// <summary>
		/// DrainPipesDischargeUnderBridge
		/// </summary>
		Через водоотводные трубки со сбросом под мостовое сооружение,
		/// <summary>
		/// DrainPipesWaterSupply
		/// </summary>
		Через водоотводные трубки с отводом воды по водопроводу (лотку, трубе) вдоль мостового сооружения,
		/// <summary>
		/// WaterSlopes
		/// </summary>
		Сток воды вдоль проезжей части за счет уклонов за пределы мостового сооружения,
		/// <summary>
		/// WaterDischargeSidewalks
		/// </summary>
		Сброс воды поперек мостового сооружения через тротуары,
		/// <summary>
		/// ByTrays
		/// </summary>
		По лоткам (продольным или поперечным) за пределы мостового сооружения,
		/// <summary>
		/// TheGapsCarriageway
		/// </summary>
		Через зазоры в проезжей части мостового сооружения (дощатый настил и т. д.),
		/// <summary>
		/// Combined
		/// </summary>
		Комбинированный (например, за счет уклонов и лотков),
		/// <summary>
		/// NoData
		/// </summary>
		Нет данных,
	}
}
