//Generated by EnumGenerator, 26.08.2020 10:15:25
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Типы деформационных швов 
	/// </summary>
	[Serializable]
	public enum ExpansionJointType
	{
		/// <summary>
		/// Открытый
		/// </summary>
		Opened,
		/// <summary>
		/// Закрытый
		/// </summary>
		Closed,
		/// <summary>
		/// Заполненный
		/// </summary>
		Filled,
		/// <summary>
		/// Перекрытый
		/// </summary>
		Overlapped,
		/// <summary>
		/// Откатный
		/// </summary>
		Retractable,
		/// <summary>
		/// Нет данных
		/// </summary>
		NoData,
	}
}
