//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Типы деформационных швов 
	/// </summary>
	[Serializable]
	public enum ExpansionJointType : byte
	{
		/// <summary>
		/// Opened
		/// </summary>
		Открытый,
		/// <summary>
		/// Closed
		/// </summary>
		Закрытый,
		/// <summary>
		/// Filled
		/// </summary>
		Заполненный,
		/// <summary>
		/// Overlapped
		/// </summary>
		Перекрытый,
		/// <summary>
		/// Retractable
		/// </summary>
		Откатный,
		/// <summary>
		/// NoData
		/// </summary>
		Нет данных,
	}
}
