//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Тип перил
	/// </summary>
	[Serializable]
	public enum RailingsType : byte
	{
		/// <summary>
		/// None
		/// </summary>
		Перила отсутствуют,
		/// <summary>
		/// Metallic
		/// </summary>
		Металлические (секционные или непрерывные),
		/// <summary>
		/// FerroncreteMetalGrating
		/// </summary>
		Железобетонный поручень с металлической решеткой,
		/// <summary>
		/// FerroconcreteLlatticeOrSolidWall
		/// </summary>
		Железобетонные (решетчатые или со сплошной стенкой),
		/// <summary>
		/// Wood
		/// </summary>
		Деревянные,
		/// <summary>
		/// Combined
		/// </summary>
		Комбинированные,
		/// <summary>
		/// NoData
		/// </summary>
		Нет данных,
	}
}
