//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Регуляционные сооружения
	/// </summary>
	[Serializable]
	public enum RegulatoryStructures : byte
	{
		/// <summary>
		/// JetGuideSlopeReinforcement
		/// </summary>
		Струенаправляющая дамба с различными видами укрепления откосов,
		/// <summary>
		/// JetGuideWithTraverses
		/// </summary>
		Струенаправляющая дамба с траверсами,
		/// <summary>
		/// StrengtheningCoastVariousStructures
		/// </summary>
		Укрепление берега различными конструкциями,
		/// <summary>
		/// JetGuideShoreReinforcement
		/// </summary>
		Струенаправляющая дамба и укрепление берега,
		/// <summary>
		/// Cone
		/// </summary>
		Конус,
		/// <summary>
		/// RetainingOrFenceWall
		/// </summary>
		Подпорная или заборная стенка,
		/// <summary>
		/// None
		/// </summary>
		Регуляционных сооружений нет,
	}
}
