//Generated by EnumGenerator, 22.09.2020 12:17:50
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Укрепление
	/// </summary>
	[Serializable]
	public enum Strenghtening : byte
	{
		/// <summary>
		/// Odernovka
		/// </summary>
		Одерновка,
		/// <summary>
		/// RoughPaving
		/// </summary>
		Каменная наброска, мощение,
		/// <summary>
		/// MonolithicConcrete
		/// </summary>
		Монолитный бетон,
		/// <summary>
		/// FerroconcreteSlabs
		/// </summary>
		Сборные ж.б. плиты,
		/// <summary>
		/// Mattresses
		/// </summary>
		Тюфяки, матрасы-рено,
		/// <summary>
		/// LatticeFerroconcreteGravelBackfill
		/// </summary>
		Решетчатые ж.б. конструкции с щебеночной засыпкой,
		/// <summary>
		/// Gabions
		/// </summary>
		Габионы,
		/// <summary>
		/// GeotextileGravelBackfill
		/// </summary>
		Геотекстиль с щебеночной засыпкой,
		/// <summary>
		/// None
		/// </summary>
		Нет укрепления,
	}
}
