//Generated by EnumGenerator, 02.09.2020 11:38:32
using System;

namespace ITS.Core.Bridges.Domain.Enums
{
	/// <summary>
	/// Тест2
	/// </summary>
	[Serializable]
	[Flags]
	public enum Test2 : uint
	{
		/// <summary>
		/// Нет данных
		/// </summary>
		NoData = 0,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 1,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 2,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 4,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 8,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 16,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 32,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 64,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 128,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 256,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 512,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 1024,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 2048,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 4096,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 8192,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 16384,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 32768,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 65536,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 131072,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 262144,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 524288,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 1048576,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 2097152,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 4194304,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 8388608,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 16777216,
		/// <summary>
		/// Test2
		/// </summary>
		Тест2 = 33554432,
	}
}
