//Generated by MigrationGenerator, 28.05.2021 13:35:44
using System.Data;
using Migrator.Framework;

namespace ITS.DbMigration.Core
{
	/// <summary>
	/// Миграция для создания схемы
	/// </summary>
	[Migration(202105281335)]
	public class Migration202105281335 : Migration
	{
		public override void Up()
		{
			Database.AddTable("adrplan_city", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("code", DbType.String),
					new Column("okato", DbType.String),
					new Column("oktmo", DbType.String),
					new Column("city_name_id", DbType.Int64),
					new Column("city_type_id", DbType.Int64),
				});
			Database.AddTable("adrplan_city_district", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("code", DbType.String),
					new Column("district_name_id", DbType.Int64),
				});
			Database.AddTable("adrplan_city_district_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_city_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_city_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_country", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
					new Column("name_alternative", DbType.String),
					new Column("name_short", DbType.String),
				});
			Database.AddTable("adrplan_federal_district", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
					new Column("abbreviature", DbType.String),
				});
			Database.AddTable("adrplan_municipal_district", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("code", DbType.String),
					new Column("okato", DbType.String),
					new Column("oktmo", DbType.String),
					new Column("district_name_id", DbType.Int64),
					new Column("district_type_id", DbType.Int64),
					new Column("type_and_name_order_id", DbType.Int64),
				});
			Database.AddTable("adrplan_municipal_district_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_municipal_district_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_street", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("code", DbType.String),
					new Column("cadastre_number", DbType.String),
					new Column("street_name_id", DbType.Int64),
					new Column("street_type_id", DbType.Int64),
					new Column("type_and_name_order_id", DbType.Int64),
				});
			Database.AddTable("adrplan_street_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_street_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_subject_area", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
					new Column("code", DbType.String),
					new Column("okato", DbType.String),
					new Column("oktmo", DbType.String),
					new Column("subject_type_id", DbType.Int64),
					new Column("type_and_name_order_id", DbType.Int64),
				});
			Database.AddTable("adrplan_subject_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_city_district_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_city_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_city_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_municipal_district_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_municipal_district_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_street_name", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("name", DbType.String),
				});
			Database.AddTable("adrplan_street_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});
			Database.AddTable("adrplan_subject_type", new[]
				{
					new Column("id", DbType.Int64, ColumnProperty.PrimaryKey),
					new Column("type_name", DbType.String),
					new Column("type_name_short", DbType.String),
				});

			Database.AddForeignKey("city_to_city_name_0", "adrplan_city", "city_name_id", "adrplan_city_name", "id");
			Database.AddForeignKey("city_to_city_type_1", "adrplan_city", "city_type_id", "adrplan_city_type", "id");
			Database.AddForeignKey("city_district_to_city_district_name_0", "adrplan_city_district", "district_name_id", "adrplan_city_district_name", "id");
			Database.AddForeignKey("municipal_district_to_municipal_district_name_0", "adrplan_municipal_district", "district_name_id", "adrplan_municipal_district_name", "id");
			Database.AddForeignKey("municipal_district_to_municipal_district_type_1", "adrplan_municipal_district", "district_type_id", "adrplan_municipal_district_type", "id");
			Database.AddForeignKey("street_to_street_name_0", "adrplan_street", "street_name_id", "adrplan_street_name", "id");
			Database.AddForeignKey("street_to_street_type_1", "adrplan_street", "street_type_id", "adrplan_street_type", "id");
			Database.AddForeignKey("subject_area_to_subject_type_0", "adrplan_subject_area", "subject_type_id", "adrplan_subject_type", "id");
			
		}

		public override void Down()
		{
			//Database.ExecuteQuery("DELETE FROM adrplan_city");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_district");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_district_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_country");
			//Database.ExecuteQuery("DELETE FROM adrplan_federal_district");
			//Database.ExecuteQuery("DELETE FROM adrplan_municipal_district");
			//Database.ExecuteQuery("DELETE FROM adrplan_municipal_district_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_municipal_district_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_street");
			//Database.ExecuteQuery("DELETE FROM adrplan_street_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_street_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_subject_area");
			//Database.ExecuteQuery("DELETE FROM adrplan_subject_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_district_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_city_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_municipal_district_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_municipal_district_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_street_name");
			//Database.ExecuteQuery("DELETE FROM adrplan_street_type");
			//Database.ExecuteQuery("DELETE FROM adrplan_subject_type");

			Database.RemoveForeignKey("adrplan_city", "city_to_city_name_0");
			Database.RemoveForeignKey("adrplan_city", "city_to_city_type_1");
			Database.RemoveForeignKey("adrplan_city_district", "city_district_to_city_district_name_0");
			Database.RemoveForeignKey("adrplan_municipal_district", "municipal_district_to_municipal_district_name_0");
			Database.RemoveForeignKey("adrplan_municipal_district", "municipal_district_to_municipal_district_type_1");
			Database.RemoveForeignKey("adrplan_street", "street_to_street_name_0");
			Database.RemoveForeignKey("adrplan_street", "street_to_street_type_1");
			Database.RemoveForeignKey("adrplan_subject_area", "subject_area_to_subject_type_0");

			Database.RemoveTable("adrplan_city");
			Database.RemoveTable("adrplan_city_district");
			Database.RemoveTable("adrplan_city_district_name");
			Database.RemoveTable("adrplan_city_name");
			Database.RemoveTable("adrplan_city_type");
			Database.RemoveTable("adrplan_country");
			Database.RemoveTable("adrplan_federal_district");
			Database.RemoveTable("adrplan_municipal_district");
			Database.RemoveTable("adrplan_municipal_district_name");
			Database.RemoveTable("adrplan_municipal_district_type");
			Database.RemoveTable("adrplan_street");
			Database.RemoveTable("adrplan_street_name");
			Database.RemoveTable("adrplan_street_type");
			Database.RemoveTable("adrplan_subject_area");
			Database.RemoveTable("adrplan_subject_type");
			Database.RemoveTable("adrplan_city_district_name");
			Database.RemoveTable("adrplan_city_name");
			Database.RemoveTable("adrplan_city_type");
			Database.RemoveTable("adrplan_municipal_district_name");
			Database.RemoveTable("adrplan_municipal_district_type");
			Database.RemoveTable("adrplan_street_name");
			Database.RemoveTable("adrplan_street_type");
			Database.RemoveTable("adrplan_subject_type");
		}
	}
}
