//Generated by MigrationGenerator, 02.11.2020 13:22:32
using System.Data;
using Migrator.Framework;

namespace ITS.DbMigration.Bridges
{
	/// <summary>
	/// Миграция для создания схемы
	/// </summary>
	[Migration(202011021322)]
	public class Migration202011021322 : Migration
	{
		public override void Up()
		{
			
		}

		public override void Down()
		{
			
		}
	}
}
