//Generated by MigrationGenerator, 16.02.2021 11:50:15
using System.Data;
using Migrator.Framework;

namespace ITS.DbMigration.Bridges
{
	/// <summary>
	/// Миграция для корректного удаления всех структур БД при откате
	/// </summary>
	[Migration(202102161150)]
	public class Migration202102161150 : Migration
	{
		public override void Up()
		{
			
		}

		public override void Down()
		{
			
		}
	}
}
